config/routes.rb
DeclarativeAuthorizationRails3ExampleApp::Application.routes.draw do
  resources :articles, :comments
  authenticated :user do
    root :to => 'users#index'
  end
  root :to => "articles#index"
  devise_for :users
  resources :users
  namespace :admin do
    resources :users do
      put :update_roles, :on => :member
    end
    root :to => 'users#index'
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :author_name, :content, :name, :user_id
  has_many :comments, :dependent => :destroy
  validates_presence_of :name, :content
  belongs_to :user
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  attr_accessible :role_id, :user_id
  belongs_to :user
  belongs_to :role
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :article_id, :author_name, :content, :site_url, :user_id, :article
  belongs_to :article
  belongs_to :user
  validates_presence_of :author_name, :content
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :name
  has_many :assignments
  has_many :users, :through => :assignments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, 
                  :remember_me, :role_ids
  
  has_many :articles
  has_many :comments
  has_many :assignments
  has_many :roles, :through => :assignments
  
  def role_symbols
    roles.map do |role|
      role.name.underscore.to_sym
    end
  end
  
  def update_roles(role_ids)
    for role in Role.all
      if role_ids.blank? or !role_ids.include? "#{role.id}"
        roles.delete(role)
      else
        roles << role unless roles.include? role
      end
    end
  end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_filter :authenticate_user!
  filter_access_to :all
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update_roles
    @user = User.find(params[:id])
    @user.update_roles(params[:role_ids])
    redirect_to admin_user_path @user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  protected

  def permission_denied
    flash[:error] = "Sorry, you are not allowed to access that page."
    redirect_to root_url
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  filter_resource_access
  
  def index
    @articles = Article.find(:all)
  end
  
  def show
    @comment = Comment.new(:article => @article)
  end
  
  def new
  end
  
  def create
    @article.user = current_user
    if @article.save
      flash[:notice] = "Successfully created article."
      redirect_to @article
    else
      render :action => 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @article.update_attributes(params[:article])
      flash[:notice] = "Successfully updated article."
      redirect_to @article
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @article.destroy
    flash[:notice] = "Successfully destroyed article."
    redirect_to articles_url
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  filter_resource_access
  
  def new
  end
  
  def create
    @comment.user = current_user
    if @comment.save
      flash[:notice] = "Successfully created comment."
      redirect_to article_url(@comment.article_id)
    else
      render :action => 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @comment.update_attributes(params[:comment])
      flash[:notice] = "Successfully updated comment."
      redirect_to article_url(@comment.article_id)
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @comment.destroy
    flash[:notice] = "Successfully destroyed comment."
    redirect_to article_url(@comment.article_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/layout_helper.rb
module LayoutHelper
  def title(page_title, show_title = true)
    @content_for_title = page_title.to_s
    @show_title = show_title
  end

  def show_title?
    @show_title
  end
end

app/views/admin/users/index.html.haml
%h3 Users
%ul.users
  - @users.each do |user|
    %li
      = link_to user.name, [:admin, user]
      signed up #{user.created_at.to_date}
      Roles:
      = user.role_symbols

app/views/admin/users/show.html.haml
%h3 User
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}
%p
  Roles: 
%p
  = form_tag(update_roles_admin_user_path(@user), :method => :put) do
    - for role in Role.all
      = check_box_tag "role_ids[]", role.id, @user.roles.include?(role)
      = role.name
      %br
    = submit_tag "Update"

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_for @article do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.label :author_name %><br />
    <%= f.text_field :author_name %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/articles/edit.html.erb
<% title "Edit Article" %>

<%= render :partial => 'form' %>

<p>
  <%= link_to "Show", @article %> |
  <%= link_to "View All", articles_path %>
</p>

app/views/articles/index.html.erb
<% title "Articles" %>

<div id="articles">
<% for article in @articles %>
  <h2>
    <%= link_to h(article.name), article %>
    <span class="comments">(<%= pluralize(article.comments.size, 'comment') %>)</span>
  </h2>
  <div class="author">from <%=h article.author_name %> on <%= article.created_at.strftime('%b %d, %Y') %></div>
  <div class="content"><%= simple_format(article.content) %></div>
<% end %>
</div>

<% if permitted_to? :create, Article.new %>
  <p><%= link_to "New Article", new_article_path %></p>
<% end %>

app/views/articles/new.html.erb
<% title "New Article" %>

<%= render :partial => 'form' %>

<p><%= link_to "Back to List", articles_path %></p>

app/views/articles/show.html.erb
<% title @article.name %>

<p class="author"><em>from <%=h @article.author_name %></em></p>

<%= simple_format @article.content %>

<p>
  <% if permitted_to? :edit, @article %>
    <%= link_to "Edit", edit_article_path(@article) %> |
  <% end %>
  <% if permitted_to? :destroy, @article %>
    <%= link_to "Destroy", @article, :method => :delete, :confirm => "Are you sure?" %> |
  <% end %>
  <%= link_to "Back to Articles", articles_path %>
</p>

<% unless @article.comments.empty? %>
  <h2><%= pluralize(@article.comments.size, 'comment') %></h2>

  <div id="comments">
  <% for comment in @article.comments %>
    <div class="comment">
      <strong><%= link_to_unless comment.site_url.blank?, h(comment.author_name), h(comment.site_url) %></strong>
      <em>on <%= comment.created_at.strftime('%b %d, %Y at %H:%M') %></em>
      <%=simple_format comment.content %>
      <p>
        <% if permitted_to? :edit, comment %>
          <%= link_to "Edit", edit_comment_path(comment) %>
        <% end %>
        <% if permitted_to? :destroy, comment %>
          | <%= link_to "Destroy", comment, :method => :delete, :confirm => "Are you sure?" %>
        <% end %>
      </p>
    </div>
  <% end %>
  </div>
<% end %>

<% if permitted_to? :create, @comment %>
  <h3>Add your comment:</h3>
  <%= render 'comments/form' %>
<% end %>

app/views/comments/_form.html.erb
<% if @comment.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

    <ul>
    <% @comment.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_for @comment do |f| %>
  <%= f.hidden_field :article_id %>
  <p>
    <%= f.label :author_name, 'Name' %><br />
    <%= f.text_field :author_name %>
  </p>
  <p>
    <%= f.label :site_url, 'Website URL' %><br />
    <%= f.text_field :site_url %>
  </p>
  <p>
    <%= f.label :content, 'Comment' %><br />
    <%= f.text_area :content, :rows => '12', :cols => 35 %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/comments/edit.html.erb
<% title "Edit Comment" %>

<%= render :partial => 'form' %>

app/views/comments/new.html.erb
<% title "New Comment" %>

<%= render :partial => 'form' %>

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "Declarative Authorization Rails 3 Example App", root_path, :class => 'brand'
%ul.nav
  %li
    = link_to 'Articles', articles_path
  - if user_signed_in?
    %li
      = link_to 'Logout', destroy_user_session_path, :method => 'delete'
  - else
    %li
      = link_to 'Login', new_user_session_path
  - if user_signed_in?
    %li
      = link_to 'Edit account', edit_user_registration_path
  - else
    %li
      = link_to 'Sign up', new_user_registration_path
  - if user_signed_in?
    %li
      = link_to "Hi #{current_user.name}", "#"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Declarative Authorization Rails 3 Example App"
      %meta{:content => content_for?(:description) ? yield(:description) : "Declarative Authorization Rails 3 Example App", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer
      / ! end of .container
    / ! end of #main